apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.app.env }}
  {{ $name }}: {{ $value | quote | b64enc }}
  {{- end }}
