apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
stringData:
  laravel-config: |
    {{- range $name, $value := .Values.app.config }}
    {{ $name }}={{ $value }}
    {{- end }}
